### ISSUE TITLE
Faux-PR

### ISSUE THREAD

**Issue by sonnysideup** [dominodatalab/container-runtime-interface-api#1]
@steved 

https://github.com/dominodatalab/container-runtime-interface-api/blob/1ce10abe0f4be699a7cc1894731b1a96cf1cc094/.circleci/config.yml#L3

You might be able to _slurp_ this into the executor environment so you don't have to use an anchor. Minor ✂️ but not that important.

https://github.com/dominodatalab/container-runtime-interface-api/blob/1ce10abe0f4be699a7cc1894731b1a96cf1cc094/.circleci/config.yml#L33

Can we publish this to an Artifactory Pypi repository for consumption by other apps? I figure if we have that at our disposal, then let's leverage it, no?

https://github.com/dominodatalab/container-runtime-interface-api/tree/develop/tests

We should probably add some basic tests for containers/channels since we're using those interfaces in platform-apps as well.

**Comment by steved** [comment]
Tried to address point 1 in f0709f18a7ca67d90062cd5bdd6737c916ab4b8f, not sure I totally got it.

Added some tests to 8eac7fdff899b27fc732ac029e7250b10a0911c2.

Made the repo & project public https://pypi.org/project/container-runtime-interface-api/  🎉
