### ISSUE TITLE
Missing stub files in the package (v1.0.0)

### ISSUE THREAD

**Issue by yugokato** [dominodatalab/container-runtime-interface-api#79]
Stub files (eg. https://github.com/dominodatalab/container-runtime-interface-api/blob/1.0.0/src/cri_api/v1alpha2/api_pb2.pyi) are missing in the package. 
Would it be possible to include it so that an IDE recognizes the imported classes?

**Comment by steved** [comment]
Just released [2.0.0](https://github.com/dominodatalab/container-runtime-interface-api/releases/tag/2.0.0) with the additional type hints, let me know if it doesn't solve the issue!
